version: '3.8'

services:
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - local_net
networks:
    local_net:
        name: local_net
        driver: bridge
volumes:
    sailredis:
        driver: local


